### ISSUE TITLE
Auth callback broken

### ISSUE THREAD

**Issue by meanii** [niloysikdar/Spotifire#2]

**Comment by niloysikdar** [comment]
Hi @meanii , can you please elaborate on the issue?
You can check the live preview [here](https://spotifire.vercel.app/)

**Comment by meanii** [comment]
> Hi @meanii , can you please elaborate on the issue? You can check the live preview [here](https://spotifire.vercel.app/)

It's not authenticating, when I just hit to login and just redirect not even asking for any scope permissions and redirecting back to origin.

**Comment by niloysikdar** [comment]
@meanii  I think it is working fine, have you checked this [link](https://spotifire.vercel.app/) ?

**Comment by meanii** [comment]
> 

Yeah, i have opened the same link does vercel couse routing issues in react routing?

**Comment by niloysikdar** [comment]
No @meanii , it should work fine :)

**Comment by meanii** [comment]
> No @meanii , it should work fine :)

![20220113_222753](https://user-images.githubusercontent.com/62683938/149374607-76ed89c8-af6b-411c-8003-05dfd7858860.jpg)
might it's help you to go through the issue, have a look at the url.

**Comment by niloysikdar** [comment]
@meanii  The callback URL seems broken, not sure why it is showing like this!
Probably I have exhausted my user quota for the free client id :)
